/**
 * @jest-environment jsdom
 */

import "@testing-library/jest-dom";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import NewProjectForm from "./NewProjectForm";
import { createBlankProject, createMatrixProject } from "@/app/actions/project";

const push = jest.fn();

jest.mock("next/navigation", () => ({
  useRouter: () => ({ push }),
}));

jest.mock("@/app/actions/project", () => ({
  createBlankProject: jest.fn(async () => ({ success: true, id: "blank-1" })),
  createMatrixProject: jest.fn(async () => ({ success: true, id: "matrix-1" })),
}));

const mockedCreateMatrixProject = createMatrixProject as jest.MockedFunction<
  typeof createMatrixProject
>;
const mockedCreateBlankProject = createBlankProject as jest.MockedFunction<
  typeof createBlankProject
>;

describe("NewProjectForm", () => {
  beforeEach(() => {
    push.mockClear();
    mockedCreateMatrixProject.mockClear();
    mockedCreateBlankProject.mockClear();
  });

  function addScopeAndArea(scopeName = "Estructura", areaName = "Piso 1") {
    fireEvent.change(screen.getByPlaceholderText("Nueva disciplina"), {
      target: { value: scopeName },
    });
    fireEvent.click(screen.getByRole("button", { name: "Disciplina" }));
    fireEvent.change(screen.getByPlaceholderText("Nueva ubicación"), {
      target: { value: areaName },
    });
    fireEvent.click(screen.getByRole("button", { name: "Ubicación" }));
  }

  test("starts the matrix flow without autogenerated scopes or areas", () => {
    render(<NewProjectForm />);

    expect(screen.queryByText("Cantidad estructura")).not.toBeInTheDocument();
    expect(screen.queryByText("Cantidad arquitectura")).not.toBeInTheDocument();
    expect(screen.getByTestId("matrix-editor")).toBeInTheDocument();
    expect(screen.getByText("0 disciplinas · 0 ubicaciones · 0 tareas vinculadas")).toBeInTheDocument();
    expect(screen.getByText("Sin disciplinas. Agrega la primera disciplina para construir la matriz.")).toBeInTheDocument();
    expect(screen.queryByText("Piso 1")).not.toBeInTheDocument();
    expect(screen.queryByText("Piso 2")).not.toBeInTheDocument();
    expect(screen.queryByText("Estructura")).not.toBeInTheDocument();
    expect(screen.queryByText("Arquitectura")).not.toBeInTheDocument();
    expect(screen.queryByText("Redes MEP")).not.toBeInTheDocument();
  });

  test("creates the matrix project from the edited matrix draft", async () => {
    render(<NewProjectForm />);

    addScopeAndArea();
    const sidePanelQuantity = screen.getByLabelText("Cantidad Formaleta");
    fireEvent.change(sidePanelQuantity, { target: { value: "250" } });
    fireEvent.click(screen.getByRole("button", { name: "Guardar y generar cronograma" }));

    await waitFor(() => expect(mockedCreateMatrixProject).toHaveBeenCalled());
    const payload = mockedCreateMatrixProject.mock.calls[0][0];

    expect(payload.matrixPlan.cells[0].activityOverrides).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          activityId: "formaleta",
          quantity: 250,
          lastEditedFrom: "matrix",
        }),
      ]),
    );
    expect(push).toHaveBeenCalledWith("/project/matrix-1");
  });

  test("activates all matrix cells before creating the matrix project", async () => {
    render(<NewProjectForm />);

    fireEvent.change(screen.getByLabelText("Nombre"), {
      target: { value: "Edificio prueba" },
    });

    addScopeAndArea("Arquitectura", "Piso 1");
    fireEvent.change(screen.getByPlaceholderText("Nueva ubicación"), {
      target: { value: "Piso 2" },
    });
    fireEvent.click(screen.getByRole("button", { name: "Ubicación" }));

    expect(screen.getByText("1 disciplinas · 2 ubicaciones · 0 tareas vinculadas")).toBeInTheDocument();
    expect(screen.getAllByText("Inactiva")).toHaveLength(2);

    fireEvent.click(screen.getByRole("button", { name: "Activar todas las celdas" }));
    expect(screen.queryByText("Inactiva")).not.toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: "Guardar y generar cronograma" }));

    await waitFor(() => expect(mockedCreateMatrixProject).toHaveBeenCalled());
    const payload = mockedCreateMatrixProject.mock.calls[0][0];

    expect(payload.name).toBe("Edificio prueba");
    expect(payload.matrixPlan.scopeTree).toHaveLength(1);
    expect(payload.matrixPlan.areas).toHaveLength(2);
    expect(payload.matrixPlan.cells).toHaveLength(2);
    expect(payload.matrixPlan.cells).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          scopeId: expect.stringContaining("arquitectura"),
          areaId: expect.stringContaining("piso-1"),
          active: true,
          recipeId: "arquitectura-muros",
        }),
        expect.objectContaining({
          scopeId: expect.stringContaining("arquitectura"),
          areaId: expect.stringContaining("piso-2"),
          active: true,
          recipeId: "arquitectura-muros",
        }),
      ]),
    );
    expect(push).toHaveBeenCalledWith("/project/matrix-1");
  }, 15_000);

  test("creates a blank schedule only from the blank creation path", async () => {
    render(<NewProjectForm />);

    fireEvent.click(screen.getByRole("button", { name: "Crear cronograma vacío" }));
    fireEvent.change(screen.getByLabelText("Nombre del proyecto"), {
      target: { value: "Cronograma vacio controlado" },
    });
    const blankButtons = screen.getAllByRole("button", {
      name: "Crear cronograma vacío",
    });
    fireEvent.click(blankButtons[blankButtons.length - 1]);

    await waitFor(() => expect(mockedCreateBlankProject).toHaveBeenCalled());
    expect(mockedCreateBlankProject).toHaveBeenCalledWith(
      expect.objectContaining({
        name: "Cronograma vacio controlado",
        startDate: expect.any(String),
      }),
    );
    expect(mockedCreateMatrixProject).not.toHaveBeenCalled();
    expect(push).toHaveBeenCalledWith("/project/blank-1");
  });

  test("resets the matrix draft when the new-project draft key changes", () => {
    const { rerender } = render(<NewProjectForm draftKey="draft-a" />);

    fireEvent.click(screen.getByRole("button", { name: "Crear cronograma vacío" }));
    fireEvent.change(screen.getByLabelText("Nombre del proyecto"), {
      target: { value: "Borrador que no debe persistir" },
    });
    fireEvent.click(screen.getByRole("button", { name: "Crear desde Programación Matricial" }));
    addScopeAndArea();
    fireEvent.change(screen.getByLabelText("Cantidad Formaleta"), {
      target: { value: "250" },
    });
    expect(screen.getByLabelText("Cantidad Formaleta")).toHaveValue(250);

    rerender(<NewProjectForm draftKey="draft-b" />);

    expect(screen.getByTestId("matrix-editor")).toBeInTheDocument();
    expect(screen.getByText("0 disciplinas · 0 ubicaciones · 0 tareas vinculadas")).toBeInTheDocument();
    expect(screen.queryByLabelText("Cantidad Formaleta")).not.toBeInTheDocument();
    expect(screen.queryByText("Piso 1")).not.toBeInTheDocument();
    expect(screen.queryByText("Estructura")).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: "Crear cronograma vacío" }));
    expect(screen.getByLabelText("Nombre del proyecto")).toHaveValue("Nuevo cronograma");
    expect(screen.queryByDisplayValue("Borrador que no debe persistir")).not.toBeInTheDocument();
  });
});
